### ISSUE TITLE
How did you find the DINO_POOL_CONTRACT and UST_POOL_CONTRACT addresses?

### ISSUE THREAD

**Issue by kallama** [alysiahuggins/dinoswap-compound-bot#2]
I can see how to get the Fossil Farm pools via the Master Chef contract (0x1948abc5400aa1d72223882958da3bec643fb4e5) and then poolLength and poolInfo to get pool address, but that only returns pools in the Fossil Farm.

How did you find the addresses for Jurassic Pools?

**Comment by lewixlabs** [comment]
You can do a reverse search on polygon scan, searching those addresses, or simply you can find them here
https://dinoswap.exchange/jurassicpools
1. expand "Details" menu on every pool
2. click on "View Jurassic Pool Contract"
